# ───── Production Profile ─────

# MySQL - uses ENV variables (Docker injects these)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/salebazar}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:myapp_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Secure@786786}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
